```{r}
#加载安装包
library(dplyr)
library(ggsci)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(rstatix)
library(reshape)
library(WGCNA)
options(stringsAsFactors = FALSE)
```

```{r}
#导入数据
femData =read.csv("C:/genelist.csv", sep=',',header=TRUE)
datExpr = as.data.frame(t(femData[, -c(1:1)]))
names(datExpr) = femData$gene_symbol
rownames(datExpr) = names(femData[,-c(1,1)])
gsg = goodSamplesGenes(datExpr, verbose = 3) 
gsg$allOK 
dim(datExpr)
head(datExpr)
```

```{r}
if (!gsg$allOK)
{
if (sum(!gsg$goodGenes)>0)
printFlush(paste("Removing genes:", paste(names(datExpr)[!gsg$goodGenes], collapse = ", ")));
if (sum(!gsg$goodSamples)>0)
printFlush(paste("Removing samples:", paste(rownames(datExpr)[!gsg$goodSamples], collapse = ", ")));
datExpr = datExpr[gsg$goodSamples, gsg$goodGenes]
}
dim(datExpr)
```

```{r}
#通过聚类进行离群点检测
sampleTree = hclust(dist(datExpr), method ="average");
sizeGrWindow(12,9)
par(cex = 0.6)
par(mar =c(0,4,2,0))
plot(sampleTree, main ="Sample clustering to detectoutliers",sub="", xlab="", cex.lab = 1.5,
cex.axis= 1.5, cex.main = 2)
```

```{r}
#绘制阈值
abline(h = 15,col="red"); # 高度15，颜色红色
clust = cutreeStatic(sampleTree, cutHeight = 15, minSize = 10)
table(clust)
keepSamples = (clust==1)	
datExpr = datExpr[keepSamples, ]		
nGenes =ncol(datExpr)	
nSamples =nrow(datExpr)
```

```{r}
#载入性状数据
traitData = read.csv("C:/trait.csv",row.names=1,header=T,comment.char = "",check.names=F)
allTraits = traitData
dim(allTraits)
names(allTraits)
head(allTraits)
```

```{r}
fpkmSamples = rownames(datExpr) 
traitSamples =rownames(allTraits) 
traitRows = match(fpkmSamples, traitSamples) 
datTraits = allTraits[traitRows,]
rownames(datTraits) 
collectGarbage()
```

```{r}
sampleTree2 = hclust(dist(datExpr), method ="average")
traitColors = numbers2colors(datTraits, signed = FALSE);
plotDendroAndColors(sampleTree2, traitColors,
                    groupLabels =names(datTraits),
                    main ="Sample dendrogram and trait heatmap")
```

```{r}
#设置软阈值
powers = c(seq(1: 30))
sft = pickSoftThreshold(datExpr, powerVector = powers,verbose = 5)
pdf(file="C:/WGCNA.pdf",width=9,height=5)
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
abline(h=0.9,col="red")
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
ggsave("soft-thresholding power_Int.png",height = 9,width = 18)
```

```{r}
softPower =21
adjacency = adjacency(datExpr, power = softPower)
TOM = TOMsimilarity(adjacency);
dissTOM = 1-TOM
```

```{r}
geneTree = hclust(as.dist(dissTOM),method='average') 
plot(geneTree, xlab="", sub="", main = "Gene clustering on TOM-based dissimilarity",
    labels = FALSE, hang = 0.04)
```

```{r}
minModuleSize =100 #Each module contains at least 50 genes.
dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM, method='hybrid', deepSplit = 2, pamRespectsDendro = FALSE, minClusterSize = minModuleSize) 
table(dynamicMods)
dynamicColors = labels2colors (dynamicMods) 
table(dynamicColors)
pdf(file="5_Tree.pdf",width=8,height=6)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05,
                    main = "Gene dendrogram and module colors")
dev.off()
```

```{r}
#模块聚类
MEList = moduleEigengenes(datExpr, colors = dynamicColors)
MEs = MEList$eigengenes
MEDiss = 1-cor(MEs, use = "pairwise.complete.obs");
METree = hclust(as.dist(MEDiss), method = "average")
pdf(file="6_module2.pdf",width=7,height=6)
plot(METree, main = "Clustering of module eigengenes",
     xlab = "", sub = "")
```

```{r}
# 构建标签 
moduleColors = dynamicColors
colorOrder = c("grey", standardColors(50))
moduleLabels = match(moduleColors, colorOrder)-1
nGenes = ncol(datExpr) 
nSamples = nrow(datExpr) 
moduleTraitCor = cor(datTraits,MEs, use = "p") 
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples) 

wgcna <- melt(moduleTraitCor) %>% 
  cbind(melt(moduleTraitPvalue))%>%
  .[,c(1:3,6)]
head(wgcna)
colnames(wgcna)=c("v1","v2","cor","P")
MDD.wgcna <- wgcna %>%
  mutate(text = case_when(  
    P >= 0.05 ~ paste(" "), 
    P < 0.05 & P >= 0.01 ~ paste( " *"),
    P < 0.01 & P >= 0.001~ paste( " **"),
    P < 0.001 ~ paste( " ***")))
write.csv(MDD.wgcna,file = "Ast.csv")

p.orign <- ggplot(MDD.wgcna, aes(v1, v2)) + 
  geom_tile(aes(fill = cor), colour = "white", size = 0.5)+
  scale_fill_gradient2(low = "#377eb8",mid = "white",high = "#e41a1c") + 
  geom_text(aes(label=text),col ="black",size = 8) +
  theme_minimal() + 
  theme(axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        axis.title.y=element_blank(), 
        axis.text.x = element_text(angle = 45, size = 8), 
        axis.text.y = element_text(size = 8)) +
  scale_x_discrete(position = "top") 
p.orign
ggsave("C:/WGCNA-heatmap.pdf", bg="white", width = 4, height = 9)
```

```{r}
#导出模块数据
moduleColors=moduleColors
probes = colnames(datExpr)
geneInfo = data.frame(probes= probes,
                       moduleColor = moduleColors)
geneOrder =order(geneInfo$moduleColor)
geneInfo1 = geneInfo[geneOrder, ]
write.table(geneInfo1, file = "all_genes.txt",sep="\t",row.names=F,quote=F)

for (mod in 1:nrow(table(moduleColors))){  
  modules = names(table(moduleColors))[mod]
  probes = colnames(datExpr)
  inModule1 = (moduleColors == modules)
  modGenes11 = probes[inModule1]
  write.table(modGenes11, file =paste0("module_",modules,".txt"),sep="\t",row.names=F,col.names=F,quote=F)
}
```

























